#!/bin/bash

if [ $# -eq 0 ]; then
    echo -e "USAGE-SSH: $0 [SSH] [USER PROFILE]\nUSAGE-HTTPS: $0 [USER PROFILE]"
    exit 1
fi

if [[ $1 =~ ^(ssh|SSH)$ ]]; then
    awk '/ssh/ { gsub(",","",$2); print $2 }' <(curl -s "https://api.github.com/users/$2/repos") | xargs -n1 git clone
else
    awk '/clone_url/ { gsub(",","",$2); print $2 }' <(curl -s "https://api.github.com/users/$1/repos") | xargs -n1 git clone
fi
